name: "Build Push and apply TF"
on:
  workflow_dispatch:


jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3.1.0

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
     with:
          aws-access-key-id: ${{secrets.AWS_USER_KEY}}
          aws-secret-access-key: ${{secrets.AWS_USER_SECRET_KEY}}
          aws-region: "us-east-1"

    - name: Configure AWS profile
      uses: Fooji/create-aws-profile-action@v1
      with:
          profile: default
          region: us-east-1
          key:  ${{secrets.AWS_USER_KEY}}
          secret:  ${{secrets.AWS_USER_SECRET_KEY}}

    - name: Docker build nginx and  Push
      id: build-image
      env:
        ECR_REGISTRY: "891377310654.dkr.ecr.us-east-2.amazonaws.com"
        ECR_REPOSITORY: "nginx"
        IMAGE_TAG: latest
      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG . -f docker-nginx/Dockerfile
        aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 891377310654.dkr.ecr.us-east-1.amazonaws.com
        docker push 891377310654.dkr.ecr.us-east-1.amazonaws.com/nginx:latest
    
    - name: Docker build nginx and Push
      id: build-image
      env:
        ECR_REGISTRY: "891377310654.dkr.ecr.us-east-2.amazonaws.com"
        ECR_REPOSITORY: "php"
        IMAGE_TAG: latest
      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG . -f docker-php/Dockerfile
        aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 891377310654.dkr.ecr.us-east-1.amazonaws.com
        docker push 891377310654.dkr.ecr.us-east-1.amazonaws.com/nginx:latest

    
  terraform:
    name: Apply Terraform Changes
    runs-on: ubuntu-latest
    needs: [docker]
    steps:
      - uses: actions/checkout@v3.1.0
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{secrets.AWS_USER_KEY}}
          aws-secret-access-key: ${{secrets.AWS_USER_SECRET_KEY}}
          aws-region: "us-east-1"

      - name: Configure AWS profile
        uses: Fooji/create-aws-profile-action@v1
        with:
          profile: default
          region: us-east-1
          key:  ${{secrets.AWS_USER_KEY}}
          secret:  ${{secrets.AWS_USER_SECRET_KEY}}

      - name: Verification of Terraform
        run: |
          cd terraform
          terraform fmt
          terraform init
          terraform apply  --auto-approve 
