name: "Terraform and docker validate"
on:
  workflow_dispatch:
  
jobs:
  docker: 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3.1.0
    - name: Docker build nginx and Dont Push
      id: build-image
      env:
        ECR_REGISTRY: "891377310654.dkr.ecr.us-east-2.amazonaws.com"
        ECR_REPOSITORY: "nginx"
        IMAGE_TAG: latest
      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG . -f docker-nginx/Dockerfile
    
    - name: Docker build nginx and Dont Push
      id: build-image
      env:
        ECR_REGISTRY: "891377310654.dkr.ecr.us-east-2.amazonaws.com"
        ECR_REPOSITORY: "php"
        IMAGE_TAG: latest
      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG . -f docker-php/Dockerfile




  verify-terraform:
    name: Verify-TF
    runs-on: ubuntu-latest
    needs: [docker]
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout
        uses: actions/checkout@v3.1.0

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{secrets.AWS_USER_KEY}}
          aws-secret-access-key: ${{secrets.AWS_USER_SECRET_KEY}}
          aws-region: "us-east-1"

      - name: Configure AWS profile
        uses: Fooji/create-aws-profile-action@v1
        with:
          profile: default
          region: us-east-1
          key:  ${{secrets.AWS_USER_KEY}}
          secret:  ${{secrets.AWS_USER_SECRET_KEY}}

      - name: Terraform Init
        run: |
          cd terraform
          terraform fmt
          terraform init
          terraform validate
          terraform plan
